//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionRareCacti.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CollectionCactiEntities : DbContext
    {
        public CollectionCactiEntities()
            : base("name=CollectionCactiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cacti> Cacti { get; set; }
        public virtual DbSet<Country> Country { get; set; }
        public virtual DbSet<Instraction> Instraction { get; set; }
        public virtual DbSet<Show> Show { get; set; }
        public virtual DbSet<ShowCacti> ShowCacti { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
