//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CollectionRareCacti.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShowCacti
    {
        public int Id { get; set; }
        public int ShowId { get; set; }
        public int CactiId { get; set; }
        public string Achivments { get; set; }
        public string Comment { get; set; }
    
        public virtual Cacti Cacti { get; set; }
        public virtual Show Show { get; set; }
    }
}
